# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/kpackage': '@latest'
    'frameworks/krunner': '@latest'
    'frameworks/kservice': '@latest'
    'plasma/plasma-framework': 'kf5'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
